services:
  easytts:
    image: tw199501/easytts:latest
    restart: unless-stopped
    container_name: easytts
    ports:
      - '9549:3000'
    environment:
      - DEBUG=true
      - OPENAI_BASE_URL=https://openrouter.ai/api/v1/
    volumes:
      - ./audio:/app/audio
